### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by eddies** [eddies/home-dashi#2]
Visualizations fail to render in Chrome (OS X, Version 42.0.2311.135 (64-bit))with the following error:

```
crossfilter.js:1 Uncaught RangeError: Maximum call stack size exceeded
```

**Comment by eddies** [comment]
FYI, this is using the full HOME dataset (10582 rows). A 5000 row file (e.g. `head -5000 home.csv > home-subset.csv`) seems to work.
At least in Firefox on OS X, everything seems to work, even with the full dataset. However, @oliverxchen reports a "'too much recursion' in crossfilter.js, line 174" error in Firefox for Ubuntu when using the full dataset.

**Comment by eddies** [comment]
Some related reading to consider:
- https://stackoverflow.com/questions/24435439/dc-and-crossfilter-with-large-datasets
- http://ganeshiyer.net/blog/2014/07/19/big-data-visualization-using-crossfilter-and-dc-js/
- https://stackoverflow.com/questions/24184986/using-dc-js-on-the-clientside-with-crossfilter-on-the-server
- https://github.com/tomlurge/visionion
- https://groups.google.com/forum/#!topic/dc-js-user-group/gcTIH5t3lbY

**Comment by oliverxchen** [comment]
Using this test: http://adamrich.name/recursion.html my recursion limit with FF on Ubuntu is either ~5K, ~7K or ~16K. Not sure why there's a different result each time.

Using crossfilter on the server side seems like a good stopgap, but putting up a proper database seems like the 'right' way to do this for large data sets. The general types of queries would be fairly limited, but this would take quite a bit more work to implement.

**Comment by oliverxchen** [comment]
The problem was in how birth_dt was being parsed. isFinite(d.birth_dt) was always true, even for empty strings, which resulted in NaN for age_dim. The sort wasn't dealing well with the NaN's. 

I've changed it to d.birth_dt !== '' and it now works in both Firefox and Chrome.

**Comment by dsivakumar** [comment]
Seems to be a machine(RAM?) specific issue, it occurs in one m/c and works on a few others.  I have 8GB and works fine.
